# Generated by Django 4.2.7 on 2023-11-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('dark_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
