# Generated by Django 4.2.7 on 2023-12-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate_app', '0003_remove_profile_location_profile_hobbies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(default=''),
        ),
    ]
