# Generated by Django 4.2.7 on 2023-12-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate_app', '0004_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=130),
        ),
    ]
