# Generated by Django 4.2.7 on 2023-12-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate_app', '0005_alter_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='', max_length=130),
        ),
    ]
