# Generated by Django 4.2.7 on 2023-12-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate_app', '0006_rename_name_profile_firstname_profile_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
