# Generated by Django 4.2.7 on 2023-12-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate_app', '0007_remove_profile_firstname_remove_profile_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures'),
        ),
    ]
