# Generated by Django 4.2.7 on 2023-12-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate_app', '0008_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='media/profile_pictures/default.jpg', upload_to='profile_pictures'),
        ),
    ]
