# Generated by Django 5.0.1 on 2024-02-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate_app', '0016_post_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sender',
            field=models.TextField(),
        ),
    ]
