# Generated by Django 5.0.1 on 2024-02-22 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate_app', '0021_alter_post_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sender',
        ),
        migrations.AddField(
            model_name='post',
            name='post_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
