# Generated by Django 5.0.1 on 2024-03-03 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate_app', '0023_alter_joblisting_posted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='posted_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
