# Generated by Django 5.0.1 on 2024-03-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduate_app', '0025_alter_joblisting_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='user',
        ),
    ]
