# Generated by Django 5.0.1 on 2024-03-04 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate_app', '0026_remove_joblisting_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
